# Generated by Django 4.2 on 2024-01-01 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('main_image', models.FileField(blank=True, max_length=256, null=True, upload_to=user_management.models.save_profile_image)),
                ('is_delete', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(default=user_management.models.Role.get_default_role, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='user_management.role')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_admin', to='user_management.profile')),
            ],
            options={
                'db_table': 'all_languages',
                'ordering': ['name'],
            },
        ),
    ]
