# Generated by Django 4.2 on 2024-01-02 10:17

from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_globalconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=512)),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'guardian_details',
            },
        ),
        migrations.CreateModel(
            name='GuardianKids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_image', models.FileField(blank=True, max_length=256, null=True, upload_to=user_management.models.save_kid_image)),
                ('kid_name', models.CharField(max_length=256)),
                ('id_card_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'guardian_kids',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_class',
            },
        ),
        migrations.CreateModel(
            name='KidsIdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_media', models.FileField(blank=True, max_length=256, null=True, upload_to=user_management.models.save_kids_card)),
                ('i_kids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.guardiankids')),
            ],
            options={
                'db_table': 'kids_card',
            },
        ),
        migrations.AddField(
            model_name='guardiankids',
            name='i_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.schoolclass'),
        ),
        migrations.AddField(
            model_name='guardiankids',
            name='i_guardian_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.guardiandetails'),
        ),
        migrations.AddField(
            model_name='guardiankids',
            name='i_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.route'),
        ),
        migrations.AddField(
            model_name='guardiankids',
            name='i_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.school'),
        ),
    ]
