# Generated by Django 4.2 on 2024-02-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_guardiandetails_guardiankids_route_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('license_validity', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('vehicle_make', models.CharField()),
                ('vehicle_model', models.CharField()),
                ('vehicle_registration', models.CharField()),
                ('home_address', models.CharField(max_length=255)),
                ('assign_route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_management.route')),
                ('authorized_schools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.school')),
                ('i_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'db_table': 'driver_details',
            },
        ),
    ]
