# Generated by Django 4.2 on 2024-02-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_driverdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetails',
            name='date_of_employment',
        ),
    ]
