# Generated by Django 4.2 on 2024-02-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_remove_driverdetails_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetails',
            name='assign_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.route'),
        ),
    ]
