# Generated by Django 4.2 on 2024-02-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_driverdetails_assign_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[('IN PROGRESS', 1), ('COMPLETED', 2)])),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.guardiandetails')),
            ],
        ),
    ]
